// <auto-generated />
using System;
using FeedMessages.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedMessages.API.Migrations
{
    [DbContext(typeof(FeedDbContext))]
    partial class FeedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeedMessages.Domain.Entities.FeedDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("feed", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8126b8b8-996b-4da5-9ae6-3239b2c9fa23"),
                            Author = "boringwhitecollar",
                            Content = "Let’s discuss one of my favorite movies of all time: CLUE. It is such a fun film. Based on a board game, six guests arrive at an isolated mansion for dinner, drinks, and MURDER. Starring: Tim Curry, Eileen Brennan, Madeline Kahn, Christopher Lloyd, Michael McKean, Martin Mull, Lesley Ann Warren, Lee Ving, Colleen Camp, and Howard Hesseman.",
                            CreatedAt = new DateTime(2022, 11, 28, 17, 34, 58, 380, DateTimeKind.Local).AddTicks(5451),
                            LastEdited = new DateTime(2022, 11, 28, 17, 34, 58, 380, DateTimeKind.Local).AddTicks(5486),
                            TopicName = "Clue (1985)"
                        },
                        new
                        {
                            Id = new Guid("c74d8d05-7969-4148-8e16-4ecdf20675d7"),
                            Author = "BobbyCrispyGuitar",
                            Content = "The James Bond films are known for their original opening themes written by popular artists and are often played on the radio and tv. 'Live and Let Die' by Paul McCartney, 'For Your Eyes Only' by Sheena Easton, 'A View to a Kill' by Duran Duran, and 'Goldfinger' by Shirley Bassey are just a few. My personal favorite is 'Nobody Does It Better' by Carly Simon. What James Bond theme do you consider to be the best?",
                            CreatedAt = new DateTime(2022, 11, 28, 17, 34, 58, 380, DateTimeKind.Local).AddTicks(5495),
                            LastEdited = new DateTime(2022, 11, 28, 17, 34, 58, 380, DateTimeKind.Local).AddTicks(5497),
                            TopicName = "What is the greatest James Bond 007 theme song of all time?"
                        },
                        new
                        {
                            Id = new Guid("d26bdfea-b767-4b6c-9f9d-711cae5f9f0b"),
                            Author = "thorped077",
                            Content = "The below list are particular vigilante moves i absolutely love.Death Wish, Unbreakable,Death Sentence,Leon (the professional),Gran Torino,Drive,Kill Bill films(especially unbreakable, kill bill 2 , the professional)Can anyone give me any recommendations based on these vibes?Thanks, fellow movie aficionados.edited: Totally forgot about (Unforgiven 1992, which could top my entire list), Man on Fire , and Commando(1985- Pure nostalgia love and soundtrack as a kid in the 80s)r",
                            CreatedAt = new DateTime(2022, 11, 28, 17, 34, 58, 380, DateTimeKind.Local).AddTicks(5500),
                            LastEdited = new DateTime(2022, 11, 28, 17, 34, 58, 380, DateTimeKind.Local).AddTicks(5503),
                            TopicName = "Vigilante Movie Suggestions?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
