version: '3.4'

services:
  feedmessages.api:
    image: ${DOCKER_REGISTRY-}feedmessagesapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5800:80
    depends_on:
    - db

  # MySQL database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - "1435:1433"
    environment:
      MSSQL_SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"

