version: '3.4'

services:
  feedmessages.api:
    image: ${DOCKER_REGISTRY-}feedmessagesapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 5800:80
    - 7800:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/feed.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
    - db

  # MySQL database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - "1435:1433"
    environment:
      MSSQL_SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"

