version: '3.4'

networks:
  k6:
  grafana:


services:
  feedmessages.api:
    image: ${DOCKER_REGISTRY-}feedmessages
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 5800:80
    - 7800:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/feed.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
    - db

  # MySQL database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - "1435:1433"
    environment:
      MSSQL_SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"

  influxdb:
    image: influxdb:1.8
#    entrypoint: /bin/sh
#    user: root
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
#    entrypoint: /bin/sh
#    user: root
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dadshboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

