apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: feeds-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feeds-api
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 75
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 1
  desiredReplicas: 1