name: Perform load tests on production.

on:
  push:
    branches: ["main"]

jobs:
  run-K6-load-tests:
    name: locade 
    steps: ls
    name: K6 Load Test
    runs-on: self-hosted
    steps:
      - name: Perform load tests 
        run: .\scripts\commands\run_load_test
