name: Perform load tests on production.

on:
  push:
    branches: ["main"]

jobs:
  run-K6-load-tests:
    name: K6 Load Test
    runs-on: self-hosted
    steps:
      - name: Setup environment
        run: .\scripts\run-scripts\run_load_test