name: Perform load tests on production.

on:
  push:
    branches: ["main"]

jobs:
  run-K6-load-tests:
    name: K6 Load Test
    runs-on: self-hosted
    steps:
      - name: Setup environment
        run: D:\Gebruiker\Mark Goertz\School\FeedMessages\scripts\run-scripts\run-load-GET-test.ps1