name: Perform load tests on production.

on:
  push:
    branches: ["main"]

jobs:
  run-K6-load-tests:
    name: K6 Load Test
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Perform load tests 
        shell: powershell
        run: ./scripts/commands/run_load_test.ps1
